// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/api/user.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Feedback.tsx";
import * as $$2 from "./islands/NavButton.tsx";
import * as $$3 from "./islands/Tab.tsx";
import * as $$4 from "./islands/zippyButton.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/api/user.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Feedback.tsx": $$1,
    "./islands/NavButton.tsx": $$2,
    "./islands/Tab.tsx": $$3,
    "./islands/zippyButton.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
